
CONNECT datasoft/datasoft@//localhost:1521/FREEPDB1

CREATE TABLE generes (
                         id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
                         name VARCHAR2(30) NOT NULL,
                         CONSTRAINT pk_generes PRIMARY KEY (id)
);

CREATE TABLE users (
                       id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
                       full_name VARCHAR2(30) NOT NULL,
                       username VARCHAR2(20) NOT NULL,
                       passwd VARCHAR2(500) NOT NULL,
                       state VARCHAR2(3) NOT NULL,
                       CONSTRAINT pk_users PRIMARY KEY (id),
                       CONSTRAINT uq_username UNIQUE (username)
);

CREATE TABLE books (
                       id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
                       name VARCHAR2(50) NOT NULL,
                       summary VARCHAR2(500),
                       price NUMBER(6,2) NOT NULL,
                       state VARCHAR2(3) NOT NULL,
                       image VARCHAR2(500),
                       gen_id NUMBER(10) NOT NULL,
                       usr_id NUMBER(10) NOT NULL,
                       CONSTRAINT pk_books PRIMARY KEY (id),
                       CONSTRAINT fk_books_generes FOREIGN KEY (gen_id) REFERENCES generes(id),
                       CONSTRAINT fk_books_users FOREIGN KEY (usr_id) REFERENCES users(id)
);